### ISSUE TITLE
Some Time the Mod does not work (but mostly work)

### ISSUE THREAD

**Issue by ardissaps** [dangbroitsdon/Wall-Jump-Unofficial#13]
when it does not work, restart fixed them but sometimes it happen again

**Comment by dangbroitsdon** [comment]
fixed in v1.5.0, will be released either today or tomorrow

**Comment by ardissaps** [comment]
I see, thank you very much.

**Comment by dangbroitsdon** [comment]
no problemos!!!

**Comment by ardissaps** [comment]
@dangbroitsdon the problem is actually still happening, but while play sometime it works again, i do try /reload but still no effect

**Comment by dangbroitsdon** [comment]
ill dig deeper

**Comment by dangbroitsdon** [comment]
question; are you on local world or server?

**Comment by ardissaps** [comment]
> question; are you on local world or server?

I am on singleplayer only.

**Comment by dangbroitsdon** [comment]
alright i think i figured it out ill upload it to releases would you mind testing it from there?

**Comment by ardissaps** [comment]
> alright i think i figured it out ill upload it to releases would you mind testing it from there?

this one right? I only disable double jump, but I can't clink on wall. (the wall and fence jump works to, only cling does not work)

**Comment by dangbroitsdon** [comment]
there is a new release for it, there was originally a pre release in githubs releases section but i got rid of it. I tested it myself on that version and it worked fine, however I didn't test it after a set amount of time, say an hour. That could possibly be a factor in it, idk.

**Comment by dangbroitsdon** [comment]
this is also fixed now clinging is a little bit more responsive
